POST http://localhost:8080/devops_starter_war_exploded/api/login
Content-Type: application/json

{
  "username": "user",
  "password": "test"
}

###
POST http://localhost:8080/harbour_backend_war_exploded/api/owner
Content-Type: application/json

{
  "name": "Eske",
  "address": "Smedetoften",
  "phone": "31951061"
}

###
GET http://localhost:8080/devops_starter_war_exploded/api/user

###
GET http://localhost:8080/devops_starter_war_exploded/api/user/1

###
PUT http://localhost:8080/devops_starter_war_exploded/api/user/2
Content-Type: application/json

{
  "name": "Børge"
}

###
GET http://localhost:8080/devops_starter_war_exploded/api/boat

###
GET http://localhost:8080/devops_starter_war_exploded/api/boat/1

###
POST http://localhost:8080/harbour_backend_war_exploded/api/boat
Content-Type: application/json

{
  "brand": "Hjuldamper",
  "make": "2000",
  "name": "Van kaj",
  "image": ""
}

###
PUT http://localhost:8080/devops_starter_war_exploded/api/boat/1
Content-Type: application/json

{
  "brand": "Suzuki",
  "make": "c10",
  "name": "Rolf",
  "image": "",
  "harbour_id": 1
}

###
GET http://localhost:8080/devops_starter_war_exploded/api/harbour

###
GET http://localhost:8080/devops_starter_war_exploded/api/harbour/1

###
POST http://localhost:8080/harbour_backend_war_exploded/api/harbour
Content-Type: application/json

{
  "name": "Jordhavn",
  "address": "Jordhavnsvej",
  "capacity": 10000
}

###
PUT http://localhost:8080/devops_starter_war_exploded/api/harbour/2
Content-Type: application/json

{
  "name": "Nordhavn",
  "address": "Nordhavnsvej",
  "capacity": 500
}

###
PUT http://localhost:8080/harbour_backend_war_exploded/api/harbour/add/3/3
Content-Type: application/json

###
PUT http://localhost:8080/harbour_backend_war_exploded/api/owner/add/2/1
Content-Type: application/json

###
POST http://localhost:8080/devops_starter_war_exploded/api/login
Content-Type: application/json

{
  "username": "aske123",
  "password": "12345"
}

###
DELETE http://localhost:8080/harbour_backend_war_exploded/api/harbour/remove/1
Content-Type: application/json





